version: '3.7'

services:
  web:
    container_name: docker_devenv
    build: ./docker
    ports:
      - 8521:80
    privileged: true
    volumes:
      - ./public_html:/var/www/html
      
  # mariaDB
  db:
    image: mysql:5.7
    container_name: db-host_public_html
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3526:3306

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db-host_public_html
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "8522:80"
    volumes:
      - ./docker/phpmyadmin/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini      

  mail:
    image: mailhog/mailhog
    ports:
      - 8523:8025

